# Generated by Django 5.0.7 on 2026-06-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='calories',
            field=models.PositiveIntegerField(default=0, verbose_name='热量快照(kcal)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='碳水快照(g)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='脂肪快照(g)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='蛋白质快照(g)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sodium',
            field=models.PositiveIntegerField(default=0, verbose_name='钠快照(mg)'),
        ),
    ]
